-- MySQL Script generated by MySQL Workbench
-- Sun Jul  5 19:46:19 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `database` DEFAULT CHARACTER SET utf8 ;
USE `database` ;

-- -----------------------------------------------------
-- Table `database`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `database`.`Usuario` (
  `idUsuario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NULL,
  `telefono` INT UNSIGNED NULL,
  `dirección` VARCHAR(45) NOT NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  `país` VARCHAR(45) NOT NULL,
  `región` VARCHAR(45) NOT NULL,
  `códigoPostal` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database`.`Categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database`.`Categoria` ;

CREATE TABLE IF NOT EXISTS `database`.`Categoria` (
  `idCategoria` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `descripcion` TEXT NULL,
  `image` VARCHAR(45) NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `database`.`Producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database`.`Producto` ;

CREATE TABLE IF NOT EXISTS `database`.`Producto` (
  `idProducto` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `stock` INT NULL,
  `descripcion` VARCHAR(45) NULL,
  `calificacion` FLOAT NULL,
  `imagen` VARCHAR(45) NULL,
  `autor` VARCHAR(45) NOT NULL,
  `precio` INT NOT NULL,
  `descuento` INT NOT NULL,
  `peso` FLOAT NOT NULL,
  `codigo` INT NOT NULL,
  `idCategoria` INT UNSIGNED NULL,
  PRIMARY KEY (`idProducto`),
  CONSTRAINT `categor`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `database`.`Categoria` (`idCategoria`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database`.`OrdenCompra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database`.`OrdenCompra` ;

CREATE TABLE IF NOT EXISTS `database`.`OrdenCompra` (
  `idOrdenCompra` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `costoenvio` INT NOT NULL,
  `comprado` DATETIME NOT NULL,
  `tipodepago` VARCHAR(45) NOT NULL,
  `notas` VARCHAR(45) NULL,
  PRIMARY KEY (`idOrdenCompra`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database`.`Reseña`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database`.`Reseña` ;

CREATE TABLE IF NOT EXISTS `database`.`Reseña` (
  `idComentario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `calificacion` FLOAT NOT NULL,
  `comentario` VARCHAR(45) NULL,
  `publicadoen` DATETIME NOT NULL,
  `idUsuario` INT UNSIGNED NOT NULL,
  `idProducto` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idComentario`),
  CONSTRAINT `us`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `database`.`Usuario` (`idUsuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `pr`
    FOREIGN KEY (`idProducto`)
    REFERENCES `database`.`Producto` (`idProducto`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database`.`ElementoCarro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database`.`ElementoCarro` ;

CREATE TABLE IF NOT EXISTS `database`.`ElementoCarro` (
  `idElementoCarro` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `costo` INT UNSIGNED NOT NULL,
  `agregadoen` DATETIME NOT NULL,
  `idProducto` INT UNSIGNED NOT NULL,
  `idUsuario` INT UNSIGNED NULL,
  PRIMARY KEY (`idElementoCarro`),
  CONSTRAINT `usuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `database`.`Usuario` (`idUsuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `producto`
    FOREIGN KEY (`idProducto`)
    REFERENCES `database`.`Producto` (`idProducto`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database`.`OrdenProducto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database`.`OrdenProducto` ;

CREATE TABLE IF NOT EXISTS `database`.`OrdenProducto` (
  `idProducto` INT UNSIGNED NOT NULL,
  `idOrden` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idProducto`, `idOrden`),
  CONSTRAINT `prod`
    FOREIGN KEY (`idProducto`)
    REFERENCES `database`.`Producto` (`idProducto`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `ord`
    FOREIGN KEY (`idOrden`)
    REFERENCES `database`.`OrdenCompra` (`idOrdenCompra`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
